In [1]:
# Dependency
import pandas as pd

In [2]:
# Load in CSVs
jan_data = "Resources/JC-202201-citibike-tripdata.csv"
feb_data = "Resources/JC-202202-citibike-tripdata.csv"
mar_data = "Resources/JC-202203-citibike-tripdata.csv"

In [3]:
# Read CSVs
jan_pd = pd.read_csv(jan_data)
feb_pd = pd.read_csv(feb_data)
mar_pd = pd.read_csv(mar_data)

In [4]:
# Concatenate all 3 dataframes into one
nycbike_q1 = pd.concat([jan_pd,feb_pd,mar_pd])

In [5]:
# Print dataframe
nycbike_q1.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,CA5837152804D4B5,electric_bike,2022-01-26 18:50:39,2022-01-26 18:51:53,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
1,BA06A5E45B6601D2,classic_bike,2022-01-28 13:14:07,2022-01-28 13:20:23,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
2,7B6827D7B9508D93,classic_bike,2022-01-10 19:55:13,2022-01-10 20:00:37,Essex Light Rail,JC038,Essex Light Rail,JC038,40.712774,-74.036486,40.712774,-74.036486,member
3,6E5864EA6FCEC90D,electric_bike,2022-01-26 07:54:57,2022-01-26 07:55:22,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member
4,E24954255BBDE32D,electric_bike,2022-01-13 18:44:46,2022-01-13 18:45:43,12 St & Sinatra Dr N,HB201,12 St & Sinatra Dr N,HB201,40.750604,-74.024020,40.750604,-74.024020,member

In [6]:
# Export file as a CSV
nycbike_q1.to_csv("Resources/MergedData.csv", index=False, header=True)